apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: cbp-workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: compile
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "compile started..."
      - name: produce-binary
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: sleep 10
      - name: push binary
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "binary pushing..."
      - name: register-build-artifacts
        uses: https://github.com/cloudbees-io/register-build-artifact@v1
        with:
          name: myApp
          version: 1.0.0
          url: docker.io/myapp/myimg:1.0.0
          digest: ""
  test:
    needs:
      - build
    steps:
      - name: Run tests
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "tests running..."
      - name: Collect test results
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: sleep 17
      - name: Publish test results
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Sending Test Results to CBP"
  deploy:
    needs:
      - build
      - test
    steps:
      - name: Prepare Manifest
        uses: cloudbees-io/checkout@v1
      - name: Call Deploy Workflow
        uses: cloudbees-io/workflows-dispatch@main
        with:
          workflows-dispatch-file: dispatch_requests.json
          token: ${{ secrets.MY_PAT }}
